export async function generateTaskPlan(task, deadline, hours) {
  hours = Number(hours);

  let priority = "🟢 Low";
  let risk = "🟢 Low";

  if (hours >= 8) {
    priority = "🔴 High";
    risk = "🔴 High";
  } else if (hours >= 4) {
    priority = "🟡 Medium";
    risk = "🟡 Medium";
  }

  const start = new Date();

  let currentHour = start.getHours();
  let currentMinute = start.getMinutes();

  function formatTime(hour, minute) {
    const period = hour >= 12 ? "PM" : "AM";
    let h = hour % 12;
    if (h === 0) h = 12;
    return `${h}:${minute.toString().padStart(2, "0")} ${period}`;
  }

  let schedule = "";

  const sessions = Math.ceil(hours);

  for (let i = 0; i < sessions; i++) {

    const startTime = formatTime(currentHour, currentMinute);

    currentMinute += 50;

    if (currentMinute >= 60) {
      currentHour++;
      currentMinute -= 60;
    }

    const endTime = formatTime(currentHour, currentMinute);

    schedule += `🕒 ${startTime} - ${endTime}\n`;

    if (i === 0)
      schedule += "Research & Planning\n\n";
    else if (i === sessions - 1)
      schedule += "Testing & Final Review\n\n";
    else
      schedule += "Main Development\n\n";

    currentMinute += 10;

    if (currentMinute >= 60) {
      currentHour++;
      currentMinute -= 60;
    }
  }

  return `
📌 ${task}

━━━━━━━━━━━━━━━━━━━━

🔥 Priority

${priority}

⚠️ Risk

${risk}

━━━━━━━━━━━━━━━━━━━━

📅 AI Suggested Schedule

${schedule}

━━━━━━━━━━━━━━━━━━━━

💡 AI Suggestions

✔ Finish difficult work first

✔ Keep phone away

✔ Review before submission

✔ Take 10-minute breaks

━━━━━━━━━━━━━━━━━━━━

Generated by DeadlineAI 🤖
`;
}